<?php

return [
    'clinic_name' => env('CLINIC_NAME', 'MedAssist Medical Center'),
    'doctor_name' => env('CLINIC_DOCTOR_NAME', 'MedAssist AI (MBBS, MD-AI)'),
    'license' => env('CLINIC_LICENSE', 'Reg: 12345678'),
    'phone' => env('CLINIC_PHONE', '+1-800-MED-ASSIST'),
    'address' => env('CLINIC_ADDRESS', ''),
    'footer' => env('CLINIC_FOOTER', 'Generated by MedAssist System. This is a computer-generated document.'),
];
